<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "y7_fahrzeugdatenbank"
 *
 * Auto generated by Extension Builder 2015-03-24
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Y7 Fahrzeugdatenbank',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Marc Ernst',
	'author_email' => 'ernst.marc@gmail.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.2',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
			'tt_news' => '3.6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);